# create environment: conda env create -f environment.yml
# update environment: conda env update -n cd_aa2 -f environment.yml

name: cd_aa2

dependencies:
  - python
  - pip
  - ipykernel
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - pip:
    - tensorflow
    - transformers